//! TLS, against a scripted git host behind a real handshake.
//!
//! ```text
//! cargo test -p dynamic-config-git --test over_https
//! ```
//!
//! No Docker, no network and no certificate in the repository: a certificate
//! authority and a server certificate are **generated by the test that needs
//! them**, in memory, and never written anywhere. A repository with a private
//! key in it has a private key in it, whatever the README says about the key
//! being a test one.
//!
//! The host is [`common::host`] — the same one `over_http.rs` uses, the same
//! delegation to a real `git upload-pack` — with a `rustls` server connection
//! wrapped around the socket. So what is under test is exactly the part this
//! crate wrote: the `reqwest` client in `src/tls.rs`, its root store, its
//! identity, and the transport `gix` drives with it.
//!
//! # What each test is actually asking
//!
//! A TLS test that only asserts "it worked" proves nothing: a client that
//! trusts everything also works. So the pair matters — the same host, reached
//! when its authority is named and **refused when it is not** — and the
//! refusal asserts the sharper half, which is that the credential never
//! reached the wire.

mod common;

use std::io::{Read, Write};
use std::net::TcpStream;
use std::sync::Arc;

use common::host::{self, Host, Serving, Stream, Wrap};
use common::{Repository, Sandbox};
use dynamic_config::{ErrorKind, Format, RemoteSource, Value};
use dynamic_config_git::{Credential, GitSource, Keys, TlsConfig};
use rcgen::{BasicConstraints, CertificateParams, DnType, IsCa, Issuer, KeyPair, KeyUsagePurpose};
use rustls::pki_types::{CertificateDer, PrivateKeyDer};

/// A certificate and the key that signed it, as PEM and as DER.
struct Material {
    pem: String,
    key_pem: String,
    der: CertificateDer<'static>,
    key_der: PrivateKeyDer<'static>,
}

/// A private certificate authority, and certificates it will sign.
struct Authority {
    certificate: Material,
    issuer: Issuer<'static, KeyPair>,
}

impl Authority {
    fn new(name: &str) -> Self {
        let key = KeyPair::generate().expect("a key pair");

        let mut params = CertificateParams::new(Vec::new()).expect("ca parameters");
        params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
        params.key_usages = vec![
            KeyUsagePurpose::KeyCertSign,
            KeyUsagePurpose::CrlSign,
            KeyUsagePurpose::DigitalSignature,
        ];
        params.distinguished_name.push(DnType::CommonName, name);

        let certificate = params.self_signed(&key).expect("a self-signed ca");

        Self {
            certificate: Material {
                pem: certificate.pem(),
                key_pem: key.serialize_pem(),
                der: certificate.der().clone(),
                key_der: PrivateKeyDer::try_from(key.serialize_der()).expect("a pkcs8 key"),
            },
            issuer: Issuer::new(params, key),
        }
    }

    /// A certificate for `subject`, signed by this authority.
    ///
    /// `127.0.0.1` becomes an IP subject-alternative-name rather than a DNS
    /// one, which is what a loopback listener needs and what `rustls` will
    /// insist on.
    fn sign(&self, subject: &str) -> Material {
        let key = KeyPair::generate().expect("a key pair");
        let mut params = CertificateParams::new(vec![subject.to_owned()]).expect("parameters");
        params
            .distinguished_name
            .push(DnType::CommonName, subject.to_owned());

        let certificate = params.signed_by(&key, &self.issuer).expect("a signature");

        Material {
            pem: certificate.pem(),
            key_pem: key.serialize_pem(),
            der: certificate.der().clone(),
            key_der: PrivateKeyDer::try_from(key.serialize_der()).expect("a pkcs8 key"),
        }
    }
}

/// The provider, named rather than defaulted: `reqwest` selects `aws-lc-rs`
/// and picking it here too keeps one provider in one process.
fn provider() -> Arc<rustls::crypto::CryptoProvider> {
    Arc::new(rustls::crypto::aws_lc_rs::default_provider())
}

/// Wraps each accepted socket in a TLS session presenting `server`.
///
/// `require` is the authority a client certificate must be signed by, when the
/// host is one that asks for one.
fn tls(server: Material, require: Option<CertificateDer<'static>>) -> Wrap {
    let verifier = match require {
        None => rustls::server::WebPkiClientVerifier::no_client_auth(),
        Some(authority) => {
            let mut roots = rustls::RootCertStore::empty();
            roots.add(authority).expect("a client authority");

            rustls::server::WebPkiClientVerifier::builder_with_provider(roots.into(), provider())
                .build()
                .expect("a client verifier")
        }
    };

    let config = rustls::ServerConfig::builder_with_provider(provider())
        .with_safe_default_protocol_versions()
        .expect("the default protocol versions")
        .with_client_cert_verifier(verifier)
        .with_single_cert(vec![server.der], server.key_der)
        .expect("a server certificate");

    let config = Arc::new(config);

    Box::new(move |socket: TcpStream| {
        let connection = rustls::ServerConnection::new(Arc::clone(&config)).ok()?;

        Some(Box::new(rustls::StreamOwned::new(connection, socket)) as Box<dyn Stream>)
    })
}

/// A repository of three configuration files, served over HTTPS.
fn a_served_repository(
    named: &str,
    token: &str,
    authority: &Authority,
    require_client: Option<CertificateDer<'static>>,
) -> (Sandbox, Repository, Arc<Host>, String, Serving) {
    let sandbox = Sandbox::new(named);
    let repository = Repository::create(sandbox.join("origin"));

    repository.commit_together(&[
        ("conf/db.yaml", "db:\n  host: db.internal\n"),
        ("conf/server.yaml", "server:\n  port: 8080\n"),
        ("conf/limits.yaml", "limits:\n  connections: 64\n"),
    ]);

    let host = Host::new(token);
    let (url, serving) = host::serve(
        &repository,
        Arc::clone(&host),
        "https",
        tls(authority.sign("127.0.0.1"), require_client),
    );

    (sandbox, repository, host, url, serving)
}

/// **The test the feature exists for.** An enterprise host whose certificate
/// nothing on this machine trusts, reached because the caller named its
/// authority — and reading a *set* of files, which is the other half of this
/// release.
#[test]
fn a_private_certificate_authority_is_reached_when_the_caller_names_it() {
    let authority = Authority::new("dynamic-config test root");
    let (sandbox, _repository, host, url, _serving) =
        a_served_repository("private-ca", "ghs_token", &authority, None);

    let source = GitSource::builder(&url)
        .path(Keys::prefix("conf"))
        .format(Format::Yaml)
        .credential(Credential::token("ghs_token"))
        .tls(TlsConfig::new().with_ca_certificate_pem(authority.certificate.pem.clone()))
        .cache_dir(sandbox.join("cache"))
        .build()
        .unwrap();

    let document = source.fetch().expect("the authority was named");
    let tree = Value::parse(&document.text, Format::Yaml).expect("one merged document");

    assert_eq!(
        tree.get("db.host"),
        Some(&Value::String("db.internal".to_owned()))
    );
    assert_eq!(tree.get("server.port"), Some(&Value::Integer(8080)));
    assert_eq!(tree.get("limits.connections"), Some(&Value::Integer(64)));

    // And the credential really did go over the TLS connection: this crate does
    // not enable `http-client-insecure-credentials`, so a token on the wire
    // here is a token inside a handshake.
    assert!(
        !host.presented().is_empty()
            && host
                .presented()
                .iter()
                .all(|password| password == "ghs_token"),
        "{:?}",
        host.presented()
    );
}

/// The same material from a file rather than from bytes, because that is what
/// a Kubernetes secret mount produces and the two spellings must not drift.
#[test]
fn the_same_authority_works_when_it_is_named_as_a_file() {
    let authority = Authority::new("dynamic-config test root");
    let (sandbox, _repository, _host, url, _serving) =
        a_served_repository("private-ca-file", "ghs_token", &authority, None);

    let bundle = sandbox.join("private-ca.pem");
    std::fs::write(&bundle, &authority.certificate.pem).unwrap();

    let source = GitSource::builder(&url)
        .path("conf/db.yaml")
        .credential(Credential::token("ghs_token"))
        .tls(TlsConfig::new().with_ca_certificate_file(&bundle))
        .cache_dir(sandbox.join("cache"))
        .build()
        .unwrap();

    assert!(source.fetch().unwrap().text.contains("db.internal"));
}

/// **The half that proves the other half.** The same host, not named, is
/// refused — and the assertion that matters is not that the fetch failed but
/// that the token never left this process. A fetch presents its credential
/// before it has received anything, so a client that shrugged at an unknown
/// issuer would have handed a token to whoever held the certificate.
#[test]
fn a_host_this_machine_does_not_trust_is_refused_before_the_token_is_offered() {
    let authority = Authority::new("dynamic-config test root");
    let stranger = Authority::new("somebody else entirely");

    let (sandbox, _repository, host, url, _serving) =
        a_served_repository("untrusted", "ghs_hunter2-token", &authority, None);

    for (named, tls) in [
        // Trusting the wrong authority, through this crate's transport.
        (
            "wrong-authority",
            TlsConfig::new().with_ca_certificate_pem(stranger.certificate.pem.clone()),
        ),
        // ...and the same host through `gix`'s own transport, which trusts the
        // platform's store and nothing else. The private CA is not in it
        // either, and this is the behaviour that existed before this feature.
        ("no-authority", TlsConfig::new()),
    ] {
        let error = GitSource::builder(&url)
            .path("conf/db.yaml")
            .credential(Credential::token("ghs_hunter2-token"))
            .tls(tls)
            .cache_dir(sandbox.join(named))
            .build()
            .unwrap()
            .fetch()
            .expect_err("nothing here signed that certificate");

        assert_eq!(
            error.kind(),
            ErrorKind::Remote,
            "an untrusted certificate is not a credential problem: {error}"
        );
        assert!(!error.to_string().contains("hunter2"), "{named}: {error}");
        assert!(
            error.to_string().contains("certificate"),
            "a TLS refusal has to say it was the certificate, or the next \
             person spends an afternoon on it: {error}"
        );
    }

    assert!(
        host.connections() >= 2,
        "both attempts should have reached the listener: {}",
        host.connections()
    );
    assert!(
        host.presented().is_empty(),
        "the token must not survive a handshake this client refused: {:?}",
        host.presented()
    );
}

/// mTLS: a host that will not talk to a client it cannot identify.
#[test]
fn a_client_certificate_is_presented_to_a_host_that_asks_for_one() {
    let authority = Authority::new("dynamic-config test root");
    let client = authority.sign("app.internal");

    let (sandbox, _repository, _host, url, _serving) = a_served_repository(
        "mtls",
        "ghs_token",
        &authority,
        Some(authority.certificate.der.clone()),
    );

    let refused = GitSource::builder(&url)
        .path("conf/db.yaml")
        .credential(Credential::token("ghs_token"))
        .tls(TlsConfig::new().with_ca_certificate_pem(authority.certificate.pem.clone()))
        .cache_dir(sandbox.join("without"))
        .build()
        .unwrap()
        .fetch()
        .expect_err("the host wants a client certificate and got none");

    assert_eq!(refused.kind(), ErrorKind::Remote, "{refused}");

    let source = GitSource::builder(&url)
        .path("conf/db.yaml")
        .credential(Credential::token("ghs_token"))
        .tls(
            TlsConfig::new()
                .with_ca_certificate_pem(authority.certificate.pem.clone())
                .with_client_certificate_pem(client.pem.clone(), client.key_pem.clone()),
        )
        .cache_dir(sandbox.join("with"))
        .build()
        .unwrap();

    assert!(
        source.fetch().unwrap().text.contains("db.internal"),
        "the same host, with the certificate it asked for"
    );
}

/// The planted-credential test this path owes: a token in the remote url must
/// not reach the error a TLS failure produces, and a TLS failure is the one
/// error in this crate that `reqwest` renders rather than this crate.
#[test]
fn a_token_in_the_url_never_reaches_a_tls_failure() {
    let authority = Authority::new("dynamic-config test root");
    let stranger = Authority::new("somebody else entirely");

    let (sandbox, _repository, _host, url, _serving) =
        a_served_repository("planted-tls", "ghs_token", &authority, None);

    let with_credential = url.replace("https://", "https://x-access-token:ghs_hunter2@");

    let error = GitSource::builder(&with_credential)
        .path("conf/db.yaml")
        .tls(TlsConfig::new().with_ca_certificate_pem(stranger.certificate.pem.clone()))
        .cache_dir(sandbox.join("cache"))
        .build()
        .unwrap()
        .fetch()
        .expect_err("that authority did not sign this host's certificate");

    let printed = format!("{error} {error:?}");

    assert!(!printed.contains("hunter2"), "{printed}");
    assert!(printed.contains("x-access-token:***@"), "{printed}");
}

/// The watch loop over TLS, on a set of files: the transport is rebuilt per
/// fetch, so a poll loop must not accumulate anything or stop working on the
/// second tick.
#[test]
fn a_second_fetch_over_tls_builds_a_second_transport_and_still_works() {
    let authority = Authority::new("dynamic-config test root");
    let (sandbox, repository, host, url, _serving) =
        a_served_repository("repeated", "ghs_token", &authority, None);

    let source = GitSource::builder(&url)
        .path(Keys::several(["conf/db.yaml", "conf/server.yaml"]))
        .credential(Credential::token("ghs_token"))
        .tls(TlsConfig::new().with_ca_certificate_pem(authority.certificate.pem.clone()))
        .cache_dir(sandbox.join("cache"))
        .build()
        .unwrap();

    assert!(source.fetch().unwrap().text.contains("db.internal"));
    assert_eq!(host.transfers(), 1, "the first fetch has to transfer");

    // Unchanged: a ref advertisement and no objects, exactly as over plain
    // HTTP. The transport being ours changes nothing about that.
    source.fetch().expect("a second fetch");
    assert_eq!(host.transfers(), 1, "an unchanged ref transfers nothing");

    repository.commit_together(&[("conf/db.yaml", "db:\n  host: db-replica.internal\n")]);

    assert!(
        source.fetch().unwrap().text.contains("db-replica.internal"),
        "and a moved branch is still the point"
    );
}

/// **A host that accepts the connection and then says nothing is given up on.**
///
/// The failure `with_timeout` did not cover, and the reason this transport sets
/// a deadline on every read rather than only on connecting: a connect deadline
/// bounds a host that never answers the SYN, and this one answers it, completes
/// the TLS handshake, reads the request and then holds the socket open saying
/// nothing. `gix`'s interrupt flag is checked between packets while a pack is
/// being received, so it never fires here — nothing has arrived to be between.
///
/// The fetch runs on a thread so that a regression is a failing test rather
/// than a test suite that never finishes.
#[test]
fn a_host_that_accepts_and_then_says_nothing_is_given_up_on() {
    let authority = Authority::new("dynamic-config test root");
    let server = authority.sign("127.0.0.1");

    let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("a loopback port");
    let url = format!("https://{}/config.git", listener.local_addr().unwrap());

    let config = Arc::new(
        rustls::ServerConfig::builder_with_provider(provider())
            .with_safe_default_protocol_versions()
            .unwrap()
            .with_client_cert_verifier(rustls::server::WebPkiClientVerifier::no_client_auth())
            .with_single_cert(vec![server.der], server.key_der)
            .unwrap(),
    );

    let silent = std::thread::spawn(move || {
        let Ok(socket) = listener.accept().map(|(socket, _)| socket) else {
            return;
        };
        let Ok(connection) = rustls::ServerConnection::new(config) else {
            return;
        };

        let mut stream = rustls::StreamOwned::new(connection, socket);
        let mut scratch = [0u8; 1024];
        let _ = stream.read(&mut scratch);

        // Held open, and silent. A closed socket would be an ordinary error and
        // would prove nothing about the deadline.
        std::thread::sleep(std::time::Duration::from_secs(6));
    });

    let sandbox = Sandbox::new("silent");
    let source = GitSource::builder(&url)
        .path("conf/db.yaml")
        .credential(Credential::token("ghs_token"))
        .tls(TlsConfig::new().with_ca_certificate_pem(authority.certificate.pem.clone()))
        .cache_dir(sandbox.join("cache"))
        .with_timeout(std::time::Duration::from_secs(1))
        .build()
        .unwrap();

    let (finished, outcome) = std::sync::mpsc::channel();
    let started = std::time::Instant::now();

    std::thread::spawn(move || {
        let _ = finished.send(source.fetch().err().map(|error| error.to_string()));
    });

    let result = outcome
        .recv_timeout(std::time::Duration::from_secs(30))
        .expect("a fetch bounded at a second must not outlive the host's silence");

    // Well inside the six seconds the host stays silent for: a fetch that
    // returned only because the host finally hung up would pass every
    // assertion below and prove nothing.
    assert!(
        started.elapsed() < std::time::Duration::from_secs(4),
        "the deadline, not the host, has to be what ended this: {:?}",
        started.elapsed()
    );

    let error = result.expect("the host never answered");

    assert!(error.contains("did not answer within"), "{error}");
    assert!(
        error.contains("1s"),
        "the deadline should name itself: {error}"
    );

    let _ = silent.join();
}

/// A redirect is not followed, because every request this transport makes
/// carries a credential and a redirect is a stranger's opportunity to be handed
/// it. The refusal names itself rather than surfacing as a protocol error.
#[test]
fn a_redirect_is_refused_and_says_why() {
    let authority = Authority::new("dynamic-config test root");
    let server = authority.sign("127.0.0.1");

    let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("a loopback port");
    let url = format!("https://{}/config.git", listener.local_addr().unwrap());

    let config = {
        let verifier = rustls::server::WebPkiClientVerifier::no_client_auth();

        Arc::new(
            rustls::ServerConfig::builder_with_provider(provider())
                .with_safe_default_protocol_versions()
                .unwrap()
                .with_client_cert_verifier(verifier)
                .with_single_cert(vec![server.der], server.key_der)
                .unwrap(),
        )
    };

    let redirecting = std::thread::spawn(move || {
        let Ok(socket) = listener.accept().map(|(socket, _)| socket) else {
            return;
        };
        let Ok(connection) = rustls::ServerConnection::new(config) else {
            return;
        };

        let mut stream = rustls::StreamOwned::new(connection, socket);
        let mut scratch = [0u8; 1024];
        let _ = stream.read(&mut scratch);
        let _ = stream.write_all(
            b"HTTP/1.1 302 Found\r\nLocation: https://elsewhere.invalid/config.git\r\n\
              Content-Length: 0\r\nConnection: close\r\n\r\n",
        );
        let _ = stream.flush();
    });

    let sandbox = Sandbox::new("redirect");
    let error = GitSource::builder(&url)
        .path("conf/db.yaml")
        .credential(Credential::token("ghs_token"))
        .tls(TlsConfig::new().with_ca_certificate_pem(authority.certificate.pem.clone()))
        .cache_dir(sandbox.join("cache"))
        .build()
        .unwrap()
        .fetch()
        .expect_err("the host answered with a redirect");

    assert!(
        error.to_string().contains("does not follow"),
        "the refusal should explain itself: {error}"
    );

    let _ = redirecting.join();
}
